# Render Blueprint: HRMS Lite
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: hrms-lite-api
    runtime: python
    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-lite-db
          property: connectionString

databases:
  - name: hrms-lite-db
    plan: free
